Petland Shop/Areas/Admin/Controllers/AdminCategoriesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using Petland_Shop.Helpper;
using Petland_Shop.Models;


namespace Petland_Shop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminCategoriesController : Controller
    {
        private readonly DbMarketsContext _context;
        public INotyfService _notyfService { get; }
        public AdminCategoriesController(DbMarketsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminCategories
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lsCategorys = _context.Categories
                .AsNoTracking()
                .OrderBy(x => x.CatId);
            PagedList<Category> models = new PagedList<Category>(lsCategorys, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CatId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/AdminCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CatId,CatName,Description,ParentId,Levels,Ordering,Published,Thumb,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                //Xu ly Thumb
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string imageName = Utilities.SEOUrl(category.CatName) + extension;
                    category.Thumb = await Utilities.UploadFile(fThumb, @"category", imageName.ToLower());
                }
                if (string.IsNullOrEmpty(category.Thumb)) category.Thumb = "default.jpg";
                category.Alias = Utilities.SEOUrl(category.CatName);
                _context.Add(category);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm mới thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/AdminCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CatId,CatName,Description,ParentId,Levels,Ordering,Published,Thumb,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != category.CatId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string imageName = Utilities.SEOUrl(category.CatName) + extension;
                        category.Thumb = await Utilities.UploadFile(fThumb, @"category", imageName.ToLower());
                    }
                    if (string.IsNullOrEmpty(category.Thumb)) category.Thumb = "default.jpg";
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Chỉnh sửa thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CatId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CatId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/AdminCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CatId == id);
        }
    }
}

Petland Shop/Areas/Admin/Views/AdminCategories/Create.cshtml
@model Petland_Shop.Models.Category

@{
    ViewData["Title"] = "Tạo mới danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}

    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Tạo mới danh mục sản phẩm</a>
                <span class="breadcrumb-item active">Tạo mới danh mục</span>
            </nav>
        </div>
    </div>

    <form asp-controller="AdminCategories" asp-action="Create" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="page-header no-gutters has-tab">
            <div class="d-md-flex m-b-15 align-items-center justify-content-between">
                <div class="m-b-15">
                    <button class="btn btn-primary">
                        <i class="anticon anticon-plus-circle"></i>
                        <span>Tạo mới danh mục</span>
                    </button>
                </div>
            </div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN DANH MỤC</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
                </li>
            </ul>
        </div>
        <div class="tab-content m-t-15">
            <div class="tab-pane fade show active" id="product-edit-basic">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productName">Tên danh mục</label>
                            <input type="text" class="form-control" asp-for="CatName">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="ShortDesc">Ordering</label>
                            <input type="text" class="form-control" asp-for="Ordering">
                        </div>

                        <div class="form-group">
                            <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                            <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                            <span asp-validation-for="Thumb" class="text-danger"></span>
                        </div>
                        <div class="row">
                            <div class="form-group d-flex align-items-center">
                                <div class="checkbox">
                                    <input asp-for="Published" type="checkbox" />
                                    <label for="Published">Public</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-option">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productSize">Title</label>
                            <input type="text" class="form-control" asp-for="Title">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                            <input type="text" class="form-control" asp-for="MetaDesc">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productFit">MetaKey</label>
                            <input type="text" class="form-control" asp-for="MetaKey">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productFit">SchemaMarkup</label>
                            <input type="text" class="form-control" asp-for="SchemaMarkup">
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-description">
                <div class="card">
                    <div class="card-body">
                        <textarea class="summernote" asp-for="Description"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </form>

    @section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>

        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

Petland Shop/Areas/Admin/Views/AdminCategories/Delete.cshtml
@model Petland_Shop.Models.Category

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Levels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Levels)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ordering)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ordering)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thumb)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cover)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cover)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SchemaMarkup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SchemaMarkup)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CatId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Petland Shop/Areas/Admin/Views/AdminCategories/Details.cshtml
@model Petland_Shop.Models.Category

@{
    ViewData["Title"] = "Chi tiết Page :" + Model.CatName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Danh sách Page</a>
            <span class="breadcrumb-item active">Danh mục : @Model.CatName</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height:70px; width:70px">
                <img src="~/images/category/@Model.Thumb" alt="@Model.Title" />
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.CatName</h4>
                <p class="text-muted m-b-0">ID: #@Model.CatId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.CatId">Sửa đổi</a>
        </div>
    </div>
</div>


<h1>Chi tiết</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CatName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CatName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.Raw(Model.Description)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ordering)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ordering)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Thumb)
        </dd>


    </dl>
</div>

Petland Shop/Areas/Admin/Views/AdminCategories/Edit.cshtml
@model Petland_Shop.Models.Category

@{
    ViewData["Title"] = "Tạo mới danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}

    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Tạo mới danh mục sản phẩm</a>
                <span class="breadcrumb-item active">Sửa danh mục: @Model.CatName</span>
            </nav>
        </div>
    </div>

    <form asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.CatId" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="CatId" />
        <input type="hidden" asp-for="Thumb" />
        <div class="page-header no-gutters has-tab">
            <div class="d-md-flex m-b-15 align-items-center justify-content-between">
                <div class="m-b-15">
                    <button class="btn btn-primary">
                        <i class="anticon anticon-save"></i>
                        <span>Lưu danh mục</span>
                    </button>
                </div>
            </div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN DANH MỤC</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
                </li>
            </ul>
        </div>
        <div class="tab-content m-t-15">
            <div class="tab-pane fade show active" id="product-edit-basic">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productName">Tên danh mục</label>
                            <input type="text" class="form-control" asp-for="CatName">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="ShortDesc">Ordering</label>
                            <input type="text" class="form-control" asp-for="Ordering">
                        </div>

                        <div class="form-group">
                            <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                            <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                            <span asp-validation-for="Thumb" class="text-danger"></span>
                        </div>
                        <div class="row">
                            <div class="form-group d-flex align-items-center">
                                <div class="checkbox">
                                    <input asp-for="Published" type="checkbox" />
                                    <label for="Published">Public</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-option">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productSize">Title</label>
                            <input type="text" class="form-control" asp-for="Title">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                            <input type="text" class="form-control" asp-for="MetaDesc">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productFit">MetaKey</label>
                            <input type="text" class="form-control" asp-for="MetaKey">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productFit">SchemaMarkup</label>
                            <input type="text" class="form-control" asp-for="SchemaMarkup">
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-description">
                <div class="card">
                    <div class="card-body">
                        <textarea class="summernote" asp-for="Description"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </form>

    @section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>

        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

Petland Shop/Areas/Admin/Views/AdminCategories/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<Petland_Shop.Models.Category>
@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách danh mục sản phẩm" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <span class="breadcrumb-item active">Danh sách Page : trang @CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminCategories" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm danh mục</span></a>
            </div>
            <div class="col-lg-4 text-right">
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên danh mục</th>
                        <th>Sắp xếp</th>
                        <th>Trạng thái</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            string url = $"/{item.Alias}";
                            <tr>
                                <td>@item.CatId</td>
                                <td>
                                    <a target="_blank" href="@url">@item.CatName</a>
                                </td>
                                <td>@item.Ordering</td>
                                <td>
                                    @if (item.Published == true)
                                    {


                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Public</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Non-Public</div>
                                        </div>
                                    }


                                </td>

                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Details" asp-route-id="@item.CatId">Chi tiết</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@item.CatId">Sửa</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@item.CatId">Xóa</a>
                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>