Petland Shop/Areas/Admin/Controllers/AdminProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using Petland_Shop.Helpper;
using Petland_Shop.Models;

namespace Petland_Shop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminProductsController : Controller
    {
        private readonly DbMarketsContext _context;
        public INotyfService _notyfService { get; }
        public AdminProductsController(DbMarketsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminProducts
        public IActionResult Index(int page = 1, int CatID = 0)
        {
            var pageNumber = page;
            var pageSize = 20;

            List<Product> lsProducts = new List<Product>();
            if (CatID != 0)
            {
                lsProducts = _context.Products
                .AsNoTracking()
                .Where(x => x.CatId == CatID)
                .Include(x => x.Cat)
                .OrderBy(x => x.ProductId).ToList();
            }
            else
            {
                lsProducts = _context.Products
                .AsNoTracking()
                .Include(x => x.Cat)
                .OrderBy(x => x.ProductId).ToList();
            }



            PagedList<Product> models = new PagedList<Product>(lsProducts.AsQueryable(), pageNumber, pageSize);
            ViewBag.CurrentCateID = CatID;

            ViewBag.CurrentPage = pageNumber;

            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CatId", "CatName");

            return View(models);
        }
        public IActionResult Filtter(int CatID = 0)
        {
            var url = $"/Admin/AdminProducts?CatID={CatID}";
            if (CatID == 0)
            {
                url = $"/Admin/AdminProducts";
            }
            return Json(new { status = "success", redirectUrl = url });
        }

        // GET: Admin/AdminProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Admin/AdminProducts/Create
        public IActionResult Create()
        {
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CatId", "CatName");
            return View();
        }

        // POST: Admin/AdminProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ShortDesc,Description,CatId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetaKey,UnitsInStock")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                product.ProductName = Utilities.ToTitleCase(product.ProductName);
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(product.ProductName) + extension;
                    product.Thumb = await Utilities.UploadFile(fThumb, @"products", image.ToLower());
                }
                if (string.IsNullOrEmpty(product.Thumb)) product.Thumb = "/images/products/default.png";
                product.Alias = Utilities.SEOUrl(product.ProductName);
                product.DateModified = DateTime.Now;
                product.DateCreated = DateTime.Now;

                _context.Add(product);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm mới thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            return View(product);
        }

        // POST: Admin/AdminProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ShortDesc,Description,CatId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetaKey,UnitsInStock")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    product.ProductName = Utilities.ToTitleCase(product.ProductName);
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(product.ProductName) + extension;
                        product.Thumb = await Utilities.UploadFile(fThumb, @"products", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(product.Thumb)) product.Thumb = "/images/products/default.png";
                    product.Alias = Utilities.SEOUrl(product.ProductName);
                    product.DateModified = DateTime.Now;

                    _context.Update(product);
                    _notyfService.Success("Cập nhật thành công");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Admin/AdminProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

Petland Shop/Areas/Admin/Views/AdminProducts/Create.cshtml
@model Petland_Shop.Models.Product

@{
    ViewData["Title"] = "Tạo mới sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}
    <form asp-controller="AdminProducts" asp-action="Create" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="page-header no-gutters has-tab">
            <div class="d-md-flex m-b-15 align-items-center justify-content-between">
                <div class="m-b-15">
                    <button class="btn btn-primary">
                        <i class="anticon anticon-save"></i>
                        <span>Save</span>
                    </button>
                </div>
            </div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
                </li>
            </ul>
        </div>
        <div class="tab-content m-t-15">
            <div class="tab-pane fade show active" id="product-edit-basic">
                <div class="card">
                    <div class="card-body">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productName">Tên sản phẩm</label>
                            <input type="text" class="form-control" asp-for="ProductName">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="ShortDesc">Mô tả</label>
                            <input type="text" class="form-control" asp-for="ShortDesc">
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label class="font-weight-semibold" for="productPrice">Giá bán</label>
                                <input type="text" class="form-control" asp-for="Price">
                            </div>
                            <div class="form-group col-md-6">
                                <label class="font-weight-semibold" for="productPrice">Discount</label>
                                <input type="text" class="form-control" asp-for="Discount">
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-6">
                                <label class="font-weight-semibold" for="productCategory">Danh mục sản phẩm</label>
                                <select class="custom-select" asp-for="CatId" style="min-width: 200px;" asp-items="ViewBag.DanhMuc">
                                    <option value="" disabled selected>Chọn danh mục</option>
                                </select>
                            </div>
                            <div class="form-group col-6">
                                <label class="font-weight-semibold" for="productName">Hàng tồn kho</label>
                                <input type="text" class="form-control" asp-for="UnitsInStock">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                            <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                            <span asp-validation-for="Thumb" class="text-danger"></span>
                        </div>
                        <div class="row">
                            <div class="m-t-25">
                                <div class="form-group d-flex align-items-center">
                                    <div class="switch m-r-10">
                                        <input type="checkbox" asp-for="Active" checked="">
                                        <label for="Active"></label>
                                    </div>
                                    <label>Public</label>
                                </div>
                                <div class="form-group d-flex align-items-center">
                                    <div class="switch m-r-10">
                                        <input type="checkbox" asp-for="HomeFlag">
                                        <label for="HomeFlag"></label>
                                    </div>
                                    <label>HomeFlag</label>
                                </div>
                                <div class="form-group d-flex align-items-center">
                                    <div class="switch m-r-10">
                                        <input type="checkbox" asp-for="BestSellers">
                                        <label for="BestSellers"></label>
                                    </div>
                                    <label>BestSellers</label>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-option">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productSize">Title</label>
                            <input type="text" class="form-control" asp-for="Title">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                            <input type="text" class="form-control" asp-for="MetaDesc">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productFit">MetaKey</label>
                            <input type="text" class="form-control" asp-for="MetaKey">
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productFit">Tags</label>
                            <input type="text" class="form-control" asp-for="Tags">
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-description">
                <div class="card">
                    <div class="card-body">
                        <textarea class="summernote" asp-for="Description"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </form>

    @section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>

        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

Petland Shop/Areas/Admin/Views/AdminProducts/Delete.cshtml
@model Petland_Shop.Models.Product

@{
    ViewData["Title"] = "Thông tin sản phẩm" + Model.ProductName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminProducts" asp-action="Index" class="breadcrumb-item">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Thông tin sản phẩm : @Model.ProductName</span>
        </nav>
    </div>
</div>

<div class="card-body">
    <h4 class="card-title">Thông tin sản phẩm : @Model.ProductName</h4>
    <div class="table-responsive">
        <table class="product-info-table m-t-20">
            <tbody>
                <tr>
                    <td>ID:</td>
                    <td class="text-dark font-weight-semibold">@Model.ProductId</td>
                </tr>
                <tr>
                    <td>Tên sản phẩm:</td>
                    <td>@Model.ProductName</td>
                </tr>
                <tr>
                    <td>Mô tả ngắn:</td>
                    <td>@Model.ShortDesc</td>
                </tr>
                <tr>
                    <td>Giá:</td>
                    <td>@Model.Price</td>
                </tr>
                <tr>
                    <td>Discount:</td>
                    <td>@Model.Discount</td>
                </tr>
                <tr>
                    <td>Trạng thái:</td>
                    <td>
                        @if (Model.Active)
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" checked="" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                        else
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                    </td>
                </tr>
                <tr>
                    <td>Bestseller:</td>
                    <td>
                        @if (Model.BestSellers)
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" checked="" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                        else
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                    </td>
                </tr>
                <tr>
                    <td>HomeFlag:</td>
                    <td>
                        @if (Model.HomeFlag)
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" checked="" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                        else
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }

                    </td>
                </tr>
                <tr>
                    <td>Danh mục:</td>
                    <td>@Model.Cat.CatName</td>
                </tr>
                <tr>
                    <td>Ngày tạo:</td>
                    <td>@Model.DateCreated</td>
                </tr>
                <tr>
                    <td>Ngày chỉnh sửa:td>
                    <td>@Model.DateModified</td>
                </tr>
                <tr>
                    <td>Tiêu đề:</td>
                    <td>@Model.Title</td>
                </tr>
                <tr>
                    <td>MetaDesc:</td>
                    <td>@Model.MetaDesc</td>
                </tr>
                <tr>
                    <td>MetaKey:</td>
                    <td>@Model.MetaKey</td>
                </tr>
                <tr>
                    <td>Tags:</td>
                    <td>@Model.Tags</td>
                </tr>
                <tr>
                    <td>Ảnh đại diện:</td>
                    <td>
                        <img width="200" height="200" src="~/images/products/@Model.Thumb" alt="@Model.Title" />
                    </td>
                </tr>
                <tr>
                    <td>Mô tả sản phẩm:</td>
                    <td>@Model.Description</td>
                </tr>
                <tr>
                    <td>Xác nhận xóa:</td>
                    <td>
                        <form asp-controller="AdminProducts" asp-action="Delete" asp-route-id="@Model.ProductId">
                            <input type="hidden" asp-for="ProductId" />
                            <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
                        </form>
                    </td>
                </tr>

            </tbody>
        </table>
    </div>
</div>

Petland Shop/Areas/Admin/Views/AdminProducts/Details.cshtml
@model Petland_Shop.Models.Product

@{
    ViewData["Title"] = "Thông tin sản phẩm" + Model.ProductName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminProducts" asp-action="Index" class="breadcrumb-item">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Thông tin sản phẩm : @Model.ProductName</span>
        </nav>
    </div>
</div>

<div class="card-body">
    <h4 class="card-title">Thông tin sản phẩm : @Model.ProductName</h4>
    <div class="table-responsive">
        <table class="product-info-table m-t-20">
            <tbody>
                <tr>
                    <td>ID:</td>
                    <td class="text-dark font-weight-semibold">@Model.ProductId</td>
                </tr>
                <tr>
                    <td>Tên sản phẩm:</td>
                    <td>@Model.ProductName</td>
                </tr>
                <tr>
                    <td>Mô tả ngắn:</td>
                    <td>@Model.ShortDesc</td>
                </tr>
                <tr>
                    <td>Giá:</td>
                    <td>@Model.Price</td>
                </tr>
                <tr>
                    <td>Discount:</td>
                    <td>@Model.Discount</td>
                </tr>
                <tr>
                    <td>Trạng thái:</td>
                    <td>
                        @if (Model.Active)
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" checked="" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                        else
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                    </td>
                </tr>
                <tr>
                    <td>Bestseller:</td>
                    <td>
                        @if (Model.BestSellers)
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" checked="" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                        else
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                    </td>
                </tr>
                <tr>
                    <td>HomeFlag:</td>
                    <td>
                        @if (Model.HomeFlag)
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" checked="" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                        else
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }

                    </td>
                </tr>
                <tr>
                    <td>Danh mục:</td>
                    <td>@Model.Cat.CatName</td>
                </tr>
                <tr>
                    <td>Ngày tạo:</td>
                    <td>@Model.DateCreated</td>
                </tr>
                <tr>
                    <td>Ngày chỉnh sửa
                    <td>
                    <td>@Model.DateModified</td>
                </tr>
                <tr>
                    <td>Tiêu đề:</td>
                    <td>@Model.Title</td>
                </tr>
                <tr>
                    <td>MetaDesc:</td>
                    <td>@Model.MetaDesc</td>
                </tr>
                <tr>
                    <td>MetaKey:</td>
                    <td>@Model.MetaKey</td>
                </tr>
                <tr>
                    <td>Tags:</td>
                    <td>@Model.Tags</td>
                </tr>
                <tr>
                    <td>Ảnh đại diện:</td>
                    <td>
                        <img width="200" height="200" src="~/images/products/@Model.Thumb" alt="@Model.Title" />
                    </td>
                </tr>
                <tr>
                    <td>Mô tả sản phẩm:</td>
                    <td>@Html.Raw(Model.Description)</td>
                </tr>

            </tbody>
        </table>
    </div>
</div>